'use strict';

window.levels.level3 = {
	name:'lvl 3',
	duration: 60,
	events: {
		0: [
			// LEFTY LEFT LEFT
			{ type:'dot', color:'one', lifespan:60, 	coords:[300,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, 	coords:[300,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, 	coords:[300,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, 	coords:[300,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, 	coords:[300,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, 	coords:[300,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, 	coords:[300,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, 	coords:[300,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, 	coords:[300,495], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'five', lifespan:60, 	coords:[240,15],scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, 	coords:[240,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, 	coords:[240,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, 	coords:[240,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, 	coords:[240,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, 	coords:[240,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, 	coords:[240,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, 	coords:[240,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, 	coords:[240,495], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'four', lifespan:60, 	coords:[180,15], coreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, 	coords:[180,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, 	coords:[180,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, 	coords:[180,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, 	coords:[180,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, 	coords:[180,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, 	coords:[180,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, 	coords:[180,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, 	coords:[180,495], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'three', lifespan:60, 	coords:[120,15], coreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, 	coords:[120,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, 	coords:[120,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, 	coords:[120,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, 	coords:[120,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, 	coords:[120,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, 	coords:[120,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, 	coords:[120,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, 	coords:[120,495], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'two', lifespan:60, 	coords:[60,15], coreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, 	coords:[60,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, 	coords:[60,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, 	coords:[60,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, 	coords:[60,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, 	coords:[60,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, 	coords:[60,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, 	coords:[60,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, 	coords:[60,495], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'one', lifespan:60, 	coords:[0,15], coreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, 	coords:[0,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, 	coords:[0,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, 	coords:[0,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, 	coords:[0,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, 	coords:[0,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, 	coords:[0,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, 	coords:[0,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, 	coords:[0,495], scoreType:'DotEnemy', behavior: {} }, 
			
			
			
			
			
			// LEFT
			{ type:'dot', color:'one', lifespan:60, coords:[550,5], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[550,35], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[550,65], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[550,95], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[550,125], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[550,155], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[550,185], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[550,215], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[550,245], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[550,275], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[550,305], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[550,335], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[550,365], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[550,395], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[550,425], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[550,455], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[550,485], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[550,515], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'two', lifespan:60, coords:[500,5], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[500,35], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[500,65], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[500,95], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[500,125], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[500,155], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[500,185], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[500,215], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[500,245], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[500,275], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[500,305], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[500,335], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[500,365], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[500,395], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[500,425], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[500,455], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[500,485], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[500,515], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'three', lifespan:60, coords:[450,5], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[450,35], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[450,65], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[450,95], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[450,125], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[450,155], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[450,185], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[450,215], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[450,245], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[450,275], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[450,305], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[450,335], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[450,365], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[450,395], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[450,425], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[450,455], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[450,485], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[450,515], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'four', lifespan:60, coords:[400,5], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[400,35], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[400,65], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[400,95], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[400,125], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[400,155], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[400,185], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[400,215], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[400,245], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[400,275], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[400,305], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[400,335], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[400,365], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[400,395], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[400,425], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[400,455], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[400,485], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[400,515], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'five', lifespan:60, coords:[350,5], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[350,35], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[350,65], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[350,95], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[350,125], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[350,155], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[350,185], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[350,215], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[350,245], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[350,275], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[350,305], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[350,335], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[350,365], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[350,395], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[350,425], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[350,455], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[350,485], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[350,515], scoreType:'DotEnemy', behavior: {} }, 
			
			
			
			
			
			
			
			
			
			
			
			// RIGHT
			{ type:'dot', color:'one', lifespan:60, coords:[660,5], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[660,35], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[660,65], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[660,95], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[660,125], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[660,155], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[660,185], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[660,215], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[660,245], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[660,275], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[660,305], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[660,335], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[660,365], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[660,395], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[660,425], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[660,455], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[660,485], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, coords:[660,515], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'two', lifespan:60, coords:[710,5], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[710,35], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[710,65], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[710,95], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[710,125], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[710,155], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[710,185], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[710,215], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[710,245], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[710,275], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[710,305], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[710,335], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[710,365], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[710,395], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[710,425], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[710,455], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[710,485], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, coords:[710,515], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'three', lifespan:60, coords:[760,5], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[760,35], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[760,65], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[760,95], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[760,125], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[760,155], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[760,185], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[760,215], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[760,245], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[760,275], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[760,305], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[760,335], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[760,365], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[760,395], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[760,425], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[760,455], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[760,485], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, coords:[760,515], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'four', lifespan:60, coords:[810,5], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[810,35], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[810,65], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[810,95], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[810,125], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[810,155], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[810,185], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[810,215], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[810,245], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[810,275], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[810,305], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[810,335], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[810,365], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[810,395], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[810,425], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[810,455], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[810,485], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, coords:[810,515], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'five', lifespan:60, coords:[860,5], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[860,35], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[860,65], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[860,95], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[860,125], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[860,155], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[860,185], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[860,215], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[860,245], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[860,275], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[860,305], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[860,335], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[860,365], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[860,395], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[860,425], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[860,455], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[860,485], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, coords:[860,515], scoreType:'DotEnemy', behavior: {} }, 
			
			
			
			
			
			
			
			// RIGHTY RIGHT RIGHT
			{ type:'dot', color:'one', lifespan:60, 	coords:[910,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, 	coords:[910,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, 	coords:[910,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, 	coords:[910,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, 	coords:[910,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, 	coords:[910,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, 	coords:[910,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, 	coords:[910,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, 	coords:[910,495], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'five', lifespan:60, 	coords:[970,15],scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, 	coords:[970,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, 	coords:[970,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, 	coords:[970,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, 	coords:[970,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, 	coords:[970,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, 	coords:[970,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, 	coords:[970,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, 	coords:[970,495], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'four', lifespan:60, 	coords:[1030,15], coreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, 	coords:[1030,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, 	coords:[1030,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, 	coords:[1030,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, 	coords:[1030,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, 	coords:[1030,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, 	coords:[1030,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, 	coords:[1030,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, 	coords:[1030,495], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'three', lifespan:60, 	coords:[1090,15], coreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, 	coords:[1090,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, 	coords:[1090,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, 	coords:[1090,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, 	coords:[1090,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, 	coords:[1090,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, 	coords:[1090,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, 	coords:[1090,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, 	coords:[1090,495], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'two', lifespan:60, 	coords:[1150,15], coreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, 	coords:[1150,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, 	coords:[1150,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, 	coords:[1150,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, 	coords:[1150,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, 	coords:[1150,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, 	coords:[1150,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, 	coords:[1150,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, 	coords:[1150,495], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'one', lifespan:60, 	coords:[1210,15], coreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, 	coords:[1210,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, 	coords:[1210,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, 	coords:[1210,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:60, 	coords:[1210,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:60, 	coords:[1210,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:60, 	coords:[1210,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:60, 	coords:[1210,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:60, 	coords:[1210,495], scoreType:'DotEnemy', behavior: {} }, 
		]
	}
};
