'use strict';

window.levels.level9 = {
	id: 9, 
	name:'lvl 9',
	duration: 65,
	score: 900000, 
	events: {
		0:[
			// LEFT
			{ type:'dot', color:'one', lifespan:100, coords:[550,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:100, coords:[550,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:100, coords:[550,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:100, coords:[550,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:100, coords:[550,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:100, coords:[550,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:100, coords:[550,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:100, coords:[550,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:100, coords:[550,495], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'two', lifespan:100, coords:[500,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:100, coords:[500,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:100, coords:[500,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:100, coords:[500,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:100, coords:[500,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:100, coords:[500,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:100, coords:[500,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:100, coords:[500,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:100, coords:[500,495], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'three', lifespan:100, coords:[450,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:100, coords:[450,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:100, coords:[450,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:100, coords:[450,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:100, coords:[450,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:100, coords:[450,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:100, coords:[450,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:100, coords:[450,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:100, coords:[450,495], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'four', lifespan:100, coords:[400,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:100, coords:[400,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:100, coords:[400,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:100, coords:[400,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:100, coords:[400,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:100, coords:[400,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:100, coords:[400,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:100, coords:[400,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:100, coords:[400,495], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'five', lifespan:100, coords:[350,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:100, coords:[350,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:100, coords:[350,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:100, coords:[350,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:100, coords:[350,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:100, coords:[350,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:100, coords:[350,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:100, coords:[350,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:100, coords:[350,495], scoreType:'DotEnemy', behavior: {} }, 
			
			
			
			
			
			
			// RIGHT
			{ type:'dot', color:'one', lifespan:100, coords:[660,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:100, coords:[660,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:100, coords:[660,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:100, coords:[660,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:100, coords:[660,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:100, coords:[660,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:100, coords:[660,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:100, coords:[660,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', lifespan:100, coords:[660,495], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'two', lifespan:100, coords:[710,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:100, coords:[710,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:100, coords:[710,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:100, coords:[710,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:100, coords:[710,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:100, coords:[710,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:100, coords:[710,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:100, coords:[710,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', lifespan:100, coords:[710,495], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'three', lifespan:100, coords:[760,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:100, coords:[760,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:100, coords:[760,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:100, coords:[760,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:100, coords:[760,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:100, coords:[760,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:100, coords:[760,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:100, coords:[760,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', lifespan:100, coords:[760,495], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'four', lifespan:100, coords:[810,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:100, coords:[810,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:100, coords:[810,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:100, coords:[810,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:100, coords:[810,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:100, coords:[810,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:100, coords:[810,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:100, coords:[810,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', lifespan:100, coords:[810,495], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'five', lifespan:100, coords:[860,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:100, coords:[860,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:100, coords:[860,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:100, coords:[860,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:100, coords:[860,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:100, coords:[860,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:100, coords:[860,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:100, coords:[860,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', lifespan:100, coords:[860,495], scoreType:'DotEnemy', behavior: {} }, 
		// ],
		
		
		
		
		
		// 20: [
			// LEFTY LEFT LEFT
			{ type:'dot', color:'one', 		lifespan:100, 	coords:[300,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', 		lifespan:100, 	coords:[300,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[300,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', 	lifespan:100, 	coords:[300,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', 	lifespan:100, 	coords:[300,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', 		lifespan:100, 	coords:[300,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', 		lifespan:100, 	coords:[300,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[300,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', 	lifespan:100, 	coords:[300,495], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'five', 	lifespan:100, 	coords:[240,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', 		lifespan:100, 	coords:[240,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', 		lifespan:100, 	coords:[240,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[240,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', 	lifespan:100, 	coords:[240,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', 	lifespan:100, 	coords:[240,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', 		lifespan:100, 	coords:[240,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', 		lifespan:100, 	coords:[240,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[240,495], scoreType:'DotEnemy', behavior: {} }, 

			{ type:'dot', color:'four', 	lifespan:100, 	coords:[180,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', 	lifespan:100, 	coords:[180,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', 		lifespan:100, 	coords:[180,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', 		lifespan:100, 	coords:[180,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[180,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', 	lifespan:100, 	coords:[180,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', 	lifespan:100, 	coords:[180,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', 		lifespan:100, 	coords:[180,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', 		lifespan:100, 	coords:[180,495], scoreType:'DotEnemy', behavior: {} }, 
			
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[120,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', 	lifespan:100, 	coords:[120,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', 	lifespan:100, 	coords:[120,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', 		lifespan:100, 	coords:[120,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', 		lifespan:100, 	coords:[120,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[120,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', 	lifespan:100, 	coords:[120,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', 	lifespan:100, 	coords:[120,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', 		lifespan:100, 	coords:[120,495], scoreType:'DotEnemy', behavior: {} }, 

			{ type:'dot', color:'two', 		lifespan:100, 	coords:[60,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[60,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', 	lifespan:100, 	coords:[60,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', 	lifespan:100, 	coords:[60,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', 		lifespan:100, 	coords:[60,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', 		lifespan:100, 	coords:[60,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[60,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', 	lifespan:100, 	coords:[60,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', 	lifespan:100, 	coords:[60,495], scoreType:'DotEnemy', behavior: {} }, 

			{ type:'dot', color:'one', 		lifespan:100, 	coords:[0,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', 		lifespan:100, 	coords:[0,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[0,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', 	lifespan:100, 	coords:[0,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', 	lifespan:100, 	coords:[0,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', 		lifespan:100, 	coords:[0,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', 		lifespan:100, 	coords:[0,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[0,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', 	lifespan:100, 	coords:[0,495], scoreType:'DotEnemy', behavior: {} }, 
			
			
			
			
			
			// RIGHTY RIGHT RIGHT
			{ type:'dot', color:'one', 		lifespan:100, 	coords:[910,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', 	lifespan:100, 	coords:[910,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', 	lifespan:100, 	coords:[910,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[910,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', 		lifespan:100, 	coords:[910,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', 		lifespan:100, 	coords:[910,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', 	lifespan:100, 	coords:[910,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', 	lifespan:100, 	coords:[910,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[910,495], scoreType:'DotEnemy', behavior: {} }, 

			{ type:'dot', color:'five', 	lifespan:100, 	coords:[970,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', 	lifespan:100, 	coords:[970,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[970,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', 		lifespan:100, 	coords:[970,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', 		lifespan:100, 	coords:[970,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', 	lifespan:100, 	coords:[970,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', 	lifespan:100, 	coords:[970,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[970,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', 		lifespan:100, 	coords:[970,495], scoreType:'DotEnemy', behavior: {} }, 

			{ type:'dot', color:'four', 	lifespan:100, 	coords:[1030,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[1030,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', 		lifespan:100, 	coords:[1030,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', 		lifespan:100, 	coords:[1030,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', 	lifespan:100, 	coords:[1030,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', 	lifespan:100, 	coords:[1030,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[1030,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', 		lifespan:100, 	coords:[1030,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', 		lifespan:100, 	coords:[1030,495], scoreType:'DotEnemy', behavior: {} }, 

			{ type:'dot', color:'three', 	lifespan:100, 	coords:[1090,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', 		lifespan:100, 	coords:[1090,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', 		lifespan:100, 	coords:[1090,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', 	lifespan:100, 	coords:[1090,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', 	lifespan:100, 	coords:[1090,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[1090,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', 		lifespan:100, 	coords:[1090,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', 		lifespan:100, 	coords:[1090,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', 	lifespan:100, 	coords:[1090,495], scoreType:'DotEnemy', behavior: {} }, 

			{ type:'dot', color:'two', 		lifespan:100, 	coords:[1150,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', 		lifespan:100, 	coords:[1150,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', 	lifespan:100, 	coords:[1150,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', 	lifespan:100, 	coords:[1150,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[1150,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', 		lifespan:100, 	coords:[1150,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', 		lifespan:100, 	coords:[1150,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', 	lifespan:100, 	coords:[1150,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', 	lifespan:100, 	coords:[1150,495], scoreType:'DotEnemy', behavior: {} }, 

			{ type:'dot', color:'one', 		lifespan:100, 	coords:[1210,15], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', 	lifespan:100, 	coords:[1210,75], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', 	lifespan:100, 	coords:[1210,135], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[1210,195], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'two', 		lifespan:100, 	coords:[1210,255], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'one', 		lifespan:100, 	coords:[1210,315], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'five', 	lifespan:100, 	coords:[1210,375], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'four', 	lifespan:100, 	coords:[1210,435], scoreType:'DotEnemy', behavior: {} }, 
			{ type:'dot', color:'three', 	lifespan:100, 	coords:[1210,495], scoreType:'DotEnemy', behavior: {} }
		]
	}
};
